---
kind:       Service
apiVersion: v1
metadata:
  name: got-svc
  labels:
    app:   got-svc
spec:
  type: NodePort
  selector:
    app: got-svc
  ports:
    - name:       api
      port:       4000
      targetPort: api
      nodePort:   30405