apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.app }}
  labels:
    app: {{ .Values.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
        - name: {{ .Values.app }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          env:
          - name:  GOT_DB_NAME
            value: {{ .Values.database.name }}
          - name:  GOT_SVC_HOST
            value: {{ .Values.service.host }}
          - name:  GOT_SVC_PORT
            value: {{ .Values.service.externalPort | quote }}
          - name:  GOT_COOKIE
            valueFrom:
              secretKeyRef:
                name: got-secrets
                key:  erl-cookie
          - name:  PORT
            value: {{ .Values.service.internalPort | quote }}
          - name:  GOT_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name:  GOT_DB_USER
            valueFrom:
              secretKeyRef:
                name: got-secrets
                key:  db-user
          - name:  GOT_DB_PWD
            valueFrom:
              secretKeyRef:
                name: got-secrets
                key:  db-pwd
          - name:  GOT_DB_HOST
            value: {{ .Values.database.host }}
          - name:  GOT_DB_PORT
            value: {{ .Values.database.port | quote }}
          - name:  SECRET_KEYBASE
            valueFrom:
              secretKeyRef:
                name: got-secrets
                key:  phx-key
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
